local Rayfield = loadstring(game:HttpGet(
    "https://sirius.menu/rayfield"
))()

local Window = Rayfield:CreateWindow({
    Name = "Spam GUI v2",
    LoadingTitle = "Spam GUI",
    LoadingSubtitle = "VictHub made by textblots Bloodbox only",
    ConfigurationSaving = {
        Enabled = false
    } 
})

local MainTab = Window:CreateTab("Main", 4483362458)

MainTab:CreateSection("spam npc and props V1")

MainTab:CreateButton({
    Name = "🧟 Zombie Spam",
    Callback = function()

        Rayfield:Notify({
            Title = "Zombie Spam",
            Content = "Spawning zombies...",
            Duration = 3
        })

        while task.wait(1) do
local Event = game:GetService("ReplicatedStorage").RemoteEvents.SpawnEvents.SpawnNPCEvent
Event:FireServer(
    "Zombie",
    Vector3.new(-296.4237060546875, 33.499874114990234, -321.758056640625),
    true
)
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").RemoteEvents.SpawnEvents.SpawnNPCEvent
Event:FireServer(
    "Zombie",
    Vector3.new(-293.08596801757812, 33.500102996826172, -380.58786010742188),
    true
)
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").RemoteEvents.SpawnEvents.SpawnNPCEvent
Event:FireServer(
    "Zombie",
    Vector3.new(-296.03469848632812, 33.499916076660156, -444.13482666015625),
    true
)
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").RemoteEvents.SpawnEvents.SpawnNPCEvent
Event:FireServer(
    "Zombie",
    Vector3.new(-297.6231689453125, 33.499916076660156, -284.85836791992188),
    true
)
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").RemoteEvents.SpawnEvents.SpawnNPCEvent
Event:FireServer(
    "Zombie",
    Vector3.new(-297.8389892578125, 33.499897003173828, -245.55935668945312),
    true
)
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").RemoteEvents.SpawnEvents.SpawnNPCEvent
Event:FireServer(
    "Zombie",
    Vector3.new(-297.8389892578125, 33.499897003173828, -245.55935668945312),
    true
)
      end

    end
})

MainTab:CreateButton({
    Name = "🚗 Car Spam",
    Callback = function()

        Rayfield:Notify({
            Title = "CAR SPAMMING",
            Content = "Spawning in position...",
            Duration = 3
        })

        -- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt
while task.wait(1) do
local Event = game:GetService("ReplicatedStorage").RemoteEvents.SpawnEvents.SpawnCarEvent
Event:FireServer(
    "Military Car",
    Vector3.new(-305.70379638671875, 33.267063140869141, -168.81986999511719)
)
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").RemoteEvents.SpawnEvents.SpawnCarEvent
Event:FireServer(
    "Military Car",
    Vector3.new(-303.85321044921875, 33.267417907714844, -127.35523986816406)
)
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").RemoteEvents.SpawnEvents.SpawnCarEvent
Event:FireServer(
    "Military Car",
    Vector3.new(-302.76431274414062, 33.415393829345703, -90.263603210449219)
)
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").RemoteEvents.SpawnEvents.SpawnCarEvent
Event:FireServer(
    "Military Car",
    Vector3.new(-302.90927124023438, 33.477329254150391, -49.624641418457031)
)
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

local Event = game:GetService("ReplicatedStorage").RemoteEvents.SpawnEvents.SpawnCarEvent
Event:FireServer(
    "Military Car",
    Vector3.new(-299.61407470703125, 33.49981689453125, -15.544036865234375)
)
      end

    end
})

MainTab:CreateButton({
    Name = "Uhhh credits...?",
    Callback = function()

        Rayfield:Notify({
            Title = "Ui was made by textblots",
            Content = "Coded by textblots, used Acode.",
            Duration = 3
        })

        -- Put somethings

    end
})

Rayfield:Notify({
    Title = "BloodBox Spammer V1",
    Content = "V2 Credits to textblots via discord",
    Duration = 5
})
